spring:
  application:
    name: spring-boot-kafka-producer-consumer-error-handling
  main:
    banner-mode: #off
  banner:
    location: classpath:banner.txt
  security:
    user:
      name: admin
      password: admin
      roles: ACTUATOR_ADMIN
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic: kafka-error-handle
      properties:
        spring:
          json:
            trusted:
              packages: com.sid.app.model
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: kafka-error-handling-group-id
      auto-offset-reset: earliest
      topic: kafka-error-handle
      properties:
        spring:
          json:
            trusted:
              packages: com.sid.app.model

server:
  port: 8084

audit:
  connector:
    url: http://localhost:8085/audit
    username: audit
    password: audit

logging:
  level:
    root: INFO
    com:
      sid: INFO