spring:
    application:
        name: spring-boot-kafka-producer
    main:
        banner-mode: #off
    banner:
        location: classpath:banner.txt
    security:
        user:
            name: admin
            password: admin
            roles: ACTUATOR_ADMIN
    kafka:
       producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: all
        topic: kafka-demo
    json:
        trusted:
            packages: "com.sid.app.model"

server:
    port: 8082

audit:
    connector:
        url: http://localhost:8085/audit
        username: audit
        password: audit

logging:
    level:
        root: INFO
        com:
            sid: INFO